### ISSUE TITLE
Update Pi-hole Web-Interface 4.3.3 Fehler

### ISSUE THREAD

**Issue by Patsch-Soft** [pimanDE/translate2german#1]
Hi.
Wir lieben Deine Übersetzung. Bei einem Update auf eine neue Version von Pi-hole via "pihole -up" wird ein Fehler angezeigt. Logisch, weil im Verzeichnis /var/www/html/admin nicht mehr ein "git status" funktioniert. Einfach mit z.B. "mc" Deine Backup-Zip zurückspielen, "pihole -up" und dann noch mal Dein Script laufen lassen. Das war's. Hoffe diese kurze Erklärung war nützlich.

**Comment by pimanDE** [comment]
Danke für den Hinweis. Ich werde die Übersetzungsroutine überarbeiten.
