### ISSUE TITLE
Anzeige von Zahlenwerte mit Tausender-Punkt und Kommata

### ISSUE THREAD

**Issue by BigBen2003** [pimanDE/translate2german#10]
Nach der Übersetzung werden in den Zahlen die Tausenderpunkte bzw. Kommatas nach dem Amerikanischen Format angezeigt.

Wer das ändern will, kann das bash Script "fix_numbers_format" aus dem ZIP-Archiv ausführen.

Screenshot mit durchgeführtem Fix:
![FixZahlenFormate](https://user-images.githubusercontent.com/42717652/105233698-815dc800-5b6a-11eb-8c58-cc7f1dc73a7c.png)

Zip-Archiv (Stand: 25.01.2021):
[FormatNumbers.zip](https://github.com/pimanDE/translate2german/files/5866800/FormatNumbers.zip)

Es wird empfohlen, das Zip-Archiv in einem neuen leeren Pfad zu entpacken.

Info: Das Bash-Script "fix_numbers_format" muss unbedingt nach dem Befehl transfer2german ausgeführt werden!
Das Bash-Script wird ausschließlich beim ersten Durchlauf fehlerfrei ausgeführt.

Die Ersetzungen werden mit dem Debian-Befehl sed durchgeführt. Um die Schreibvorgänge auf einer microSD zu reduzieren, werden bei Bedarf mehrere Such- und Ersetzung-Befehle zusammengefasst und in einem Schreibvorgang wieder zurück geschrieben.

**Comment by Plagwitzer** [comment]
Ich würde das gerne mal testen.
Bin aber kein Linux User und würde mich über die notwendigen Schritte freuen.
Edit
Sehe in der Datei das im Verzeichnis germanFiles etwas sein muss.
-- script src="germanFiles\/Funcs.js"><\/script --
Ist das so richtig das die Datei fehlt?

**Comment by BigBen2003** [comment]
Hallo,

es macht nichts. In Linux muss man keine zusätzlichen Pakete installieren, damit das Script läuft.

Man muss nur das Zip-Archiv entpacken und in ein leeren Pfad entpacken.
Anschließend muss bei bedarf das Script ablauffähig gemacht werden:

`chmod +x fix_numbers_format`

Das Script basiert auf dem sed-Befehl, mit dem mit Hilfe von Reg-Expressions die Inhalte gezielt ausgewechselt werden. 

Im Script ist eine Funktion mysed enthalten die mit nur einem Parameter aufgerufen wird, alles weitere wird innerhalb der Funktion abgewickelt.

Alle Änderungen werden zunächst nur im Arbeitsspeicher gehalten. Erst am Ende werden die Änderungen zurück geschrieben.

Deswegen läuft das Script wesentlich schneller durch, als wenn jede einzelne Änderung einzeln geschrieben wird.

Habe gerade gesehen, dass im ZIP-Archiv eine Datei "Funcs.js" fehlt. Die ZIP-Archiv wurde bereits aktualisiert.

**Comment by pimanDE** [comment]
Das Komma wird nunmehr automatisch durch pi-hole gesetzt.

An dieser Stelle nochmal ein Danke an BigBen2003.

Grüße
pimanDE
