### ISSUE TITLE
Fehlende Übersetzung in der Datei scripts/pi-hole/php/gravity.php

### ISSUE THREAD

**Issue by BigBen2003** [pimanDE/translate2german#11]
In der Datei scripts/pi-hole/php/gravity.php ist eine Übersetzung übersehen worden:

return $gravitydiff->format("Blockliste vor %a days, %H Stunden und :%I Minuten aktualisiert");

In Deutsch müsste es heißen:

return $gravitydiff->format("Blockliste vor %a Tagen, %H Stunden und :%I Minuten aktualisiert");

Diese Info wird angezeigt, sobald der Mauszeiger über die Anzeige der Anzahl Blockierter Domains kommt.

Fix:
In der Datei **translate2german.sh** muss eine Zeile geändert werden:

`sudo rpl 'Blocking list updated %a days, %H:%I (hh:mm) ago' 'Blockliste vor %a days, %H Stunden und :%I Minuten aktualisiert' /var/www/html/admin/scripts/pi-hole/php/gravity.php
`

Neuer Inhalt:

`sudo rpl 'Blocking list updated %a days, %H:%I (hh:mm) ago' 'Blockliste vor %a Tagen, %H Stunden und :%I Minuten aktualisiert' /var/www/html/admin/scripts/pi-hole/php/gravity.php
`

**Comment by pimanDE** [comment]
Hallo BigBen2003,

ich danke Dir für den Hinweis. Wurde soeben gefixed.

Grüße
pimanDE
