### ISSUE TITLE
keine Installation - Pi-hole - Web Interface 5.4

### ISSUE THREAD

**Issue by marcel293** [pimanDE/translate2german#12]
Erst einmal vielen Dank für die Mühe!

Leider funktioniert das Installationsskript nicht (Pi-hole v5.2.4 Web Interface v5.4 FTL v5.7) bzw. es startet nicht im Terminal.
Habe es mit beiden Varianten (curl, einzeln).

**Fehlermeldung:**
`curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection timed out
`

Danke und Gruß
Marcel

**Comment by pimanDE** [comment]
Hallo Marcel,

an dem Script liegt es nicht, das habe ich eben geprüft.

Ich vermute, dass bei Dir die Adresse [raw.githubusercontent.com](url) auf der Blacklist des Pi-hole ist.
Setz bitte die Adresse auf die Whitelist oder deaktiviere kurz den Pi-hole und starte dann die Übersetzung noch einmal neu.

Grüße
pimanDE

**Comment by BigBen2003** [comment]
Hallo,

es kann auch an einem ungültigen DNS-Eintrag im Cache liegen.

Mit den nachstehenden Befehlen kann man den Cache löschen:

Prüft, ob der Resolved-Service aktiviert ist:
`sudo systemctl is-active systemd-resolved.service`

Falls "active" zurückgegeben wird, ist dieser aktiv.

Mit diesem Befehl kann der Cache gelöscht werden:
`systemd-resolve --flush-caches`

Weitere Infos können [hier](https://linuxize.com/post/how-to-clear-the-dns-cache/) nachgelesen werden:
