### ISSUE TITLE
Fehlende Übersetzung in Datei /var/www/html/admin/scripts/vendor/datatables.min.js

### ISSUE THREAD

**Issue by BigBen2003** [pimanDE/translate2german#13]
Auf der Webseite {IP}/admin/db_queries.php werden alle Einträge aus dem Abfragen-Protokoll aufgelistet.

Falls keine Ergebnis für eine Suche vorhanden ist, wird "No matching records found" angezeigt:

![no-matching-records-found](https://user-images.githubusercontent.com/42717652/111168800-b141ae80-85a2-11eb-998f-57aeb40904b8.png)

Mit dem nachstehenden Befehl kann die fehlende Übersetzung nachgeholt werden:

`rpl 'No matching records found' 'Keine übereinstimmende Ergebnisse gefunden' /var/www/html/admin/scripts/vendor/datatables.min.js
`

Ergebnis:
![no-matching-records-found german](https://user-images.githubusercontent.com/42717652/111168869-c1f22480-85a2-11eb-9454-6647cea7f3f5.png)

**Comment by pimanDE** [comment]
Hallo BigBen2003,

herzlichen Dank für die Info.

Ich habe das Script soeben angepasst.

Grüße
pimanDE
