### ISSUE TITLE
Nach Versuchtem Update, läuft Pihole komplett nicht mehr

### ISSUE THREAD

**Issue by RodnocNoigel** [pimanDE/translate2german#14]
Moin!
Ich habe die neue Pihole Version installieren wollen. Da ich absoluter Newbie außerhalb WIndows bin, einfach gesucht und auf dem Raspberry in der Console "pihole -up" eingegeben. Als ich mich wunderte, nicht alle Module upgedatet wurden, las ich hier bei Dir, das man vor Update erst die Übersetzung rückgängig machen solle.
Hätte ich das mal vorher gelesen. Zu spät.
Naiv wollte ich das nachholen, gabe

sudo rm -r /var/www/html/
sudo rm -r /usr/local/bin/pihole
sudo rm -r /opt/pihole/gravity.sh

ein, und seitdem läuft nichts mehr. Rein gar nichts vom Pihole.

Gibt es einen Weg wie ich die Konfig usw. retten kann um nicht alles neu einzustellen?

**Comment by pimanDE** [comment]
Hallo RodnocNoigel,

dass Dein Pi-hole nicht mehr läuft, ist sicherlich ärgerlich.

`sudo rm -r /var/www/html/`
`sudo rm -r /usr/local/bin/pihole`
`sudo rm -r /opt/pihole/gravity.sh`

war schon richtig, jedoch nur löschen nützt nichts.

Du musst auch die Sicherung anschließend zurückkopieren, so wie es in der README angegeben ist, wobei XXX das Datum der Sicherung im Format 'YYYYMMDD-HHMMSS' ist.

`sudo mv /var/www/html.sicherung.vom.XXX /var/www/html/`
`sudo mv /usr/local/bin/pihole.sicherung.vom.XXX /usr/local/bin/pihole`
`sudo mv /opt/pihole/gravity.sh.sicherung.vom.XXX /opt/pihole/gravity.sh`

Beispiel:
`sudo mv /var/www/html.sicherung.vom.20210305-121309 /var/www/html/`
`sudo mv /usr/local/bin/pihole.sicherung.vom.20210305-121309/usr/local/bin/pihole`
`sudo mv /opt/pihole/gravity.sh.sicherung.vom.20210305-121309/opt/pihole/gravity.sh`

Du kannst auch das Script zur Rückübersetzung
`bash -c "$(curl -sSL https://raw.githubusercontent.com/pimanDE/translate2german/master/restore2translate.sh)"`

verwenden.

Gruß
pimanDE

**Comment by RodnocNoigel** [comment]
Yeah, Dankeschön für Deine Hilfe, läuft wieder wie gewohnt!
