### ISSUE TITLE
Übersetzung Ja/Nein ?

### ISSUE THREAD

**Issue by Bluefish67** [pimanDE/translate2german#16]
Wird es denn eine Aktuallisierte Version geben.
Aktuell ist Pi-hole v5.7 / FTL v5.12 / Web Interface v5.9 und da funktioniert die Übersetzung leider nicht mehr.
Mfg.

**Comment by pimanDE** [comment]
Hallo Bluefish67,

ja, es wird eine aktualisierte Übersetzung geben. Ich bin dran, bitte jedoch noch um ein wenig Geduld.

Grüße
pimanDE

**Comment by pimanDE** [comment]
Die aktuelle Version der Übersetzung der Weboberfläche 5.9 auf deutsch wurde soeben veröffentlicht.

Grüße
pimanDE
