### ISSUE TITLE
nach Übersetzung bleiben Tabellen leer

### ISSUE THREAD

**Issue by MANFahrer-GF** [pimanDE/translate2german#17]
Hallo, 

danke für die Übersetzung ins deutsche leider bleiben die Tabellen auf den Seiten leer und die Tabellenüberschrift wird doppelt angezeigt. 

- Cache geleert
- Browser gewechselt 
- Log nach der Installation leer 

Beispiel: /admin/queries.php

![Bild_2021-12-29_135740](https://user-images.githubusercontent.com/29804595/147664662-7e84fcbb-a635-41ec-b20d-87fdd128593c.png)

**Comment by pimanDE** [comment]
Hi,

das sollte so nicht sein. Leider kann ich den Fehler hier nicht (reproduzierbar) feststellen.

Die Überschrift wird nicht doppelt angezeigt, sondern eine Überschrift ist oben und eine zweite ist unten.

Wie ich dem Screenshot entnehmen kann, werden aber auch andere Teile nicht übersetzt.

Versuch mal die Übersetzung rückgängig zu machen. Die Vorgehensweise findest Du unter [https://github.com/pimanDE/translate2german/blob/master/README.md](https://github.com/pimanDE/translate2german/blob/master/README.md).

Sollte dies nicht helfen dann probier bitte mal pihole -r (Repair) und starte das Script dann nochmal neu.

Gruß
pimanDE
