### ISSUE TITLE
RPL brauch seit Bullseye encoding-parm

### ISSUE THREAD

**Issue by McAntwort** [pimanDE/translate2german#18]
siehe versehentlich falsch angelegte issue
https://github.com/pimanDE/settings2pi/issues/1

bitte so abändern

`RPL --encoding UTF-8 <suche> <ersetze> <file>`

danke

**Comment by McAntwort** [comment]
workaround

```
sudo apt install -y rpl

wget https://raw.githubusercontent.com/pimanDE/translate2german/master/translate2german.sh

rpl --encoding UTF-8 "sudo rpl '" "sudo rpl --encoding UTF-8 '" ./translate2german.sh

chmod 775 translate2german.sh
sudo ./translate2german.sh
```

**Comment by pimanDE** [comment]
Hallo McAntwort,

vielen Dank für Deinen Workaround. Ich werde dies zu gegebener Zeit testen und dann umsetzen.

Grüße
pimanDE

**Comment by McAntwort** [comment]
zeile 170, das ? muss zusätzlich geslashed werden

sudo rpl --encoding UTF- '!== "to" **\\?**' '!== "zur" ?' /var/www/html/admin/scripts/pi-hole/js/index.js

**Comment by McAntwort** [comment]
alle ? in \<suche\> müssen gequotet werden, aber nciht in \<ersetze\>
z.b. Zeile 86
sudo rpl 'Did you mean to go to the admin panel\\?' 'Möchten Sie zum Administrationsbereich?' /var/www/html/pihole/index.php

runde klammern ( und ) und $ müssen auch gequotet werden

**Comment by McAntwort** [comment]
war dann doch etwas mehr als nur klammern.
so ziemlich alles was man für RegEx-Ausdrücke braucht musste geslashed werden
https://github.com/McAntwort/translate2german/blob/patch-1/translate2german.sh

läuft fehlerfrei bei mir durch, bin aber noch nicht dazu gekommen alles zu kontrollieren

**Comment by pimanDE** [comment]
Das neue Update für Bullseye ist da.

Grüße
pimanDE
