### ISSUE TITLE
Fehlermeldung nach Update auf Webinterface 5.13

### ISSUE THREAD

**Issue by defr0ke** [pimanDE/translate2german#19]
beim Versuch die deutsche Oberfläche zu installieren, kommt seit dem Update auf die neueste Version (5.13) diese Fehlermeldung:
**rpl: error: no such option: --encoding
Usage: rpl [options] old_string new_string target_file(s)**

scheinber wird der String --encoding nicht mehr erkannt oder unterstützt. Wie kann ich die deutsche Oberfläche trotzdem installieren?

**Comment by pimanDE** [comment]
Hi,

danke Dir für den Hinweis.

Der von Dir genannte Fehler tritt hier nicht auf.

`rpl --help` liefert jedoch, dass `--encoding` weiterhin unterstützt wird.

In Kürze wird ein Update auf das Webinterface 5.13 bereitgestellt. Bis dahin musst Du Dich noch gedulden.

Grüße
pimanDE

**Comment by defr0ke** [comment]
Mein Pi-hole lief noch unter Debian 10. Hab jetzt auf Debian 11 hochgestuft, jetzt funktioniert wieder die deutsche Oberfläche. Ich denke, dass der Befehl --encoding von Debian 10 nicht mehr unterstützt wird. Zu mindest wenn man das "rpl" Paket in letzter Zeit geupdated hat.

Sollte man vielleicht in der Info hier reinschreiben...

**Comment by pimanDE** [comment]
Hi,

schön dass es jetzt funktioniert. Wie jedoch in der README beschrieben, wurde das Script unter Raspberry Pi OS Bullseye vom 04.04.2022 getestet.

Grüße
pimanDE
