### ISSUE TITLE
Ausschaltmeldungen nicht übersetzt

### ISSUE THREAD

**Issue by Urs1956** [pimanDE/translate2german#2]
Hallo,
die Meldungen unter "Einstellungen" in der "Gefahrenzone"
 scheinen noch nicht übersetzt worden zu sein oder es hat nicht sauber beim Austausch geklappt:

![pi_off](https://user-images.githubusercontent.com/57187367/76099478-75f1c480-5fcb-11ea-8af7-e08dd4d44c3e.jpg)
![pi-reboot](https://user-images.githubusercontent.com/57187367/76099480-768a5b00-5fcb-11ea-8e7b-e1b47839ebb1.jpg)
![pi-Flush logs](https://user-images.githubusercontent.com/57187367/76099657-bb15f680-5fcb-11ea-894f-b0be3c2bb6a8.jpg)

**Comment by pimanDE** [comment]
Danke für den Hinweis.

Die Fehler wurden behoben.
