### ISSUE TITLE
teilweise keine Übersetzung Web Interface v.5.21

### ISSUE THREAD

**Issue by walsumerjung** [pimanDE/translate2german#23]
Hallo. 

Nach Durchführung des Skriptes unter Web-Interface v5.21 wird folgendes Protokoll ausgegeben:

Folgende Begrifflichkeiten wurden nicht übersetzt:
--------------------------------------------------
rpl:  "matchType="match""   nicht ersetzt durch   "matchType="Ergebnis""
rpl:  "plural="es""   nicht ersetzt durch   "plural="""
rpl:  "matchType="exact "   nicht ersetzt durch   "matchType="Genaues "
rpl:  "found in \$\{COL_BOLD\}exact"   nicht ersetzt durch   "gefunden in der${COL_BOLD}"
rpl:  "found in \$\{COL_BOLD\}regex"   nicht ersetzt durch   "gefunden in der ${COL_BOLD}RegEx"
rpl:  "found in \$"   nicht ersetzt durch   "gefunden in $"
rpl:  "No \$\{exact"   nicht ersetzt durch   "Kein ${exact"
rpl:  "results found for \$"   nicht ersetzt durch   "Ergebnis für $"
rpl:  "\} within the adlists"   nicht ersetzt durch   "} in den Blocklisten gefunden."
rpl:  "Over 100 \$"   nicht ersetzt durch   "Über 100 $"
rpl:  "This can be overridden using the -all option"   nicht ersetzt durch   "Dies kann mit der Option -all umgangen werden."
rpl:  "for \$\{COL_BOLD\}\${domainQuery\}\$\{COL_NC\} found in"   nicht ersetzt
durch   "für ${COL_BOLD}${domainQuery}${COL_NC} gefunden in"
rpl:  "Over \$\{count\} results found, skipping rest of file"   nicht ersetzt durch   "Über ${count} Ergebnisse, Rest der Datei wurde übersprungen."

Zuvor wurde die Übersetzung bereits auf v5.20 durchgeführt ohne Probleme. Wie beschrieben, wurde mit dem bash Befehl die Übersetzung vor der Aktualisierung auf 5.21 ohne Probleme entfernt. Die anschließende "Neuinstallation" der Übersetzung hatte dann am Ende obigen Bericht.

**Comment by defr0ke** [comment]
das stimmt... Die Übersetzung müsste mal aktualisiert werden... Es handelt sich um folgende Zeilen aus der translate2german.sh:

712-779
795-810

**Comment by pimanDE** [comment]
Hallo zusammen,

nach intensiver Prüfung konnten die o.g. fehlerhaft übersetzten Begrifflichkeiten hier nicht nachvollzogen werden (Web Interface v5.21).

Bitte einmal

`pihole -r` starten und dann das Übersetzungs-Script neu aufrufen.


Grüße
pimanDE

**Comment by walsumerjung** [comment]
Hallo pimanDE, 

pihole -r und im Anschluss das Ausführen des Übersetzungsskript hat bei mir geklappt. Alle Begriffe wurden übersetzt. 
Danke!!
