### ISSUE TITLE
Keine übersetzung von Speedtest

### ISSUE THREAD

**Issue by halfebyte** [pimanDE/translate2german#24]
Hi erst mal ein fettes Danke,

ich habe folgenden Speedtest installiert.
`curl -sSLN https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/speedtestmod/mod.sh | sudo bash -s up`
dieser wird aber nicht übersetzt, ist das richtig so oder muss ich was extra installieren?

Grüße und Danke.

**Comment by pimanDE** [comment]
Hallo halfebyte,

ja, das ist richtig so. Der Speedtest wird (zur Zeit) nicht übersetzt. Wenn, dann wird das ein extra Script werden und nicht in der translate2german.sh enthalten sein.

Grüße
pimanDE

**Comment by halfebyte** [comment]
Ok Danke
und nochmal Fettes Lob!
