### ISSUE TITLE
PiHole 5.0

### ISSUE THREAD

**Issue by Plagwitzer** [pimanDE/translate2german#3]
Wird es hier ein Update geben?

Habe das Script mal auf die 5.0 angewendet. Vieles ist schon übersetzt. Da aber etliches neu ist und zusätzlich einiges verschoben wurde fehlt doch etwas.

**Comment by pimanDE** [comment]
Hallo,

ja es wird ein Update für pi-hole 5.0 geben.
Ich bitte noch um ein wenig Geduld. Es dauert nicht mehr lange ;-)

Grüße
pimanDE
