### ISSUE TITLE
Gruppen Management

### ISSUE THREAD

**Issue by TMTYD** [pimanDE/translate2german#5]
Hi

das ist mir aufgefallen

![grafik](https://user-images.githubusercontent.com/29516076/86528177-e4755f00-bea5-11ea-9f0d-00dbc3cdd8c4.png)

das default und The default Group

**Comment by pimanDE** [comment]
Vielen Dank für den Hinweis.

Die Übersetzung ist hier leider nicht so einfach möglich, da hier kein HTML ersetzt wird, sondern direkt in die Datenbank eingegriffen wird.

Man kann den englischen Text jedoch einfach selber überschreiben.

Grüße
pimanDE

**Comment by TMTYD** [comment]
auf der Login Seite fehlt noch was 

![grafik](https://user-images.githubusercontent.com/29516076/86598463-70b67d80-bf9d-11ea-9f7a-6cae9d22b3a0.png)

**Comment by pimanDE** [comment]
Vielen Dank für den Hinweis.
Fehler ist behoben.

Grüße
pimanDE
