### ISSUE TITLE
Einfaches Bash Script zum Wiederherstellen einer Sicherung

### ISSUE THREAD

**Issue by BigBen2003** [pimanDE/translate2german#9]
Im Zip-Archiv ist eine Bash-Script-Datei restore2translate.sh enthalten, mit der spielend einfache eine beliebige Sicherung wieder zurück gespielt werden kann: 
[restore.zip](https://github.com/pimanDE/translate2german/files/5760335/restore.zip)

Nach dem Aufruf wird geprüft, ob mindestens eine Sicherung vorhanden ist.

0 > ABBRUCH!
1 > 20210102-145708

Durch Eingabe einer Zahl kann eine Sicherung ausgewählt werden.
Durch Eingabe von 0 wird das Script abgebrochen.

Im Script werden anschließend die Dateien von drei Dateien bzw. Pfade wiederhergestellt.

**Comment by Plagwitzer** [comment]
Hallo,

wo werden die Sicherungen noch gespeichert?
Ich habe die letzte Sicherung entfernt. (Nr. 4 nicht mehr da)
`Folgende Sicherungen sind vorhanden:

0 > ABBRUCH!
1 > 20230224-163004
2 > 20230324-230621
3 > 20230405-193257

Bitte die entsprechende Zahl eingeben!`

Ich habe in den Verzeichnissen und dort auch Dateien die ersetzt werden keine Sicherungen xxx.sicherung.von ... mehr stehen trotzdem steht obiges.
Wenn ich nun die Zahl 1 bis 3  auswähle, werden die Original Dateien gelöscht und es kann nichts wieder hergestellt werden.
 
Muss dann aus einer Sicherung die 2 Dateien und 1 Verzeichnis wiederherstellen.

Plagwitzer

**Comment by BigBen2003** [comment]
Hallo,

die Sicherungen werden im Pfad /opt/pihole gespeichert, wenn das Script nicht verändert wurde.

Im Script wird der Pfad in Zeile 10 vorgegeben:

path=/opt/pihole/

Der Pfad wird in Zeile 52 und 55 nochmals verwendet. In beiden Zeilen ist jedoch der Pfad fest vorgegeben.

Beim Wiederherstellen werden zunächst die Original-Dateien von PiHole komplett entfernt. Das ist richtig. Der nächste Befehl stellt die Dateien von PiHole aus der Sicherung wieder her und speichert diese im Pfad /var/www/html .

Zusätzlich wird die Programmdatei "pihole" und die Datei gravity.sh wieder hergestellt.

Wenn die Pihole-Original-Dateien zuvor gesichert werden müssen, so müssen diese separat gesichert werden.

Es ist nicht schlimm, wenn eine alte Sicherung nicht mehr vorhanden ist. Jede Sicherung beinhaltet immer eine Komplette Sicherung. Bei der Wiederherstellung wird nur eine Sicherung benötigt.
